name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "POSTGRES_USER=postgres" >> .env
          echo "POSTGRES_PASSWORD=postgres" >> .env
          echo "POSTGRES_DB=app" >> .env
          echo "DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/app" >> .env

      - name: Build and start services
        run: docker compose up -d --build

      - name: Wait for API
        run: |
          echo "Waiting for API..."

          for i in {1..30}; do
            if curl --fail http://localhost:8000/docs; then
              echo "API is ready!"
              exit 0
            fi

            echo "Retrying... ($i/30)"
            sleep 2
          done

          echo "API did not start"
          docker compose logs
          exit 1

      - name: Run tests
        run: docker compose exec -T user-service pytest

      - name: Stop containers
        if: always()
        run: docker compose down -v